
--1. 출판사들에 대한 데이터를 담기 위한 출판사 테이블(TB_PUBLISHER)
CREATE TABLE TB_PUBLISHER(
    PUB_NO NUMBER,
    PUB_NAME VARCHAR2(20),
    PHONE VARCHAR(13)
    );
--컬럼: PUB_NO(출판사 번호) --기본키(PUBLISHER_PK)
-- PUB_NAME(출판사명) --NOT NULL(PUBLICHSER_NN)
-- PHONE(출판사전화번호) --제약조건 없음
SELECT * FROM TB_PUBLISHER;

ALTER TABLE TB_PUBLISHER ADD CONSTRAINT PUBLISHER_PK PRIMARY KEY (PUB_NO);
ALTER TABLE TB_PUBLISHER MODIFY PUB_NAME NOT NULL;

--3개 정도의 샘플 데이터 추가하기==================================================
INSERT INTO TB_PUBLISHER VALUES(100,'문학동네','010-7676-7676');
INSERT INTO TB_PUBLISHER VALUES(101,'자음과모음','010-7777-7777');
INSERT INTO TB_PUBLISHER VALUES(102,'민음사','010-1212-3434');



--2. 도서들에 대한 데이터를 담기 위한 도서 테이블(TB_BOOK)
--컬럼:
-- BK_NO(도서번호) --기본키(BOOK_PK)
-- BK_TITLE(도서명) -- NOT NULL(BOOK_NN_TITLE)
-- BK_AUTHOR(저자명) -- NOT NULL(BOOK_NN_AUTHOR)
-- BK_PRICE(가격)
-- BK_STOCK(재고) --기본값 1로 지정
-- BK_PUB_NO(출판사번호) --외래키(BOOK_FK)(TB_PUBLISHER 테이블을 참조하도록)
-- 이때 참조하고 있는 부모데이터 삭제 시 자식데이터도 삭제되도록 설정
CREATE TABLE TB_BOOK(
    BK_NO NUMBER CONSTRAINT BOOK_PK PRIMARY KEY,
    BK_TITLE VARCHAR2(50) CONSTRAINT BOOK_NN_TITLE NOT NULL,
    BK_AUTHOR VARCHAR2(30) CONSTRAINT BOOK_NN_AUTHOR NOT NULL,
    BK_PRICE NUMBER,
    BK_STOCK NUMBER DEFAULT 1,
    BK_PUB_NO NUMBER CONSTRAINT BOOK_FK REFERENCES TB_PUBLISHER(PUB_NO) ON DELETE CASCADE
    );

--5개 정도의 샘플 데이터 추가하기

INSERT INTO TB_BOOK VALUES(1,'책입니다','김윤정',6000,2,100);
INSERT INTO TB_BOOK VALUES(2,'책일까요','백가영',7000,3,101);
INSERT INTO TB_BOOK VALUES(3,'책이에요','박현아',8000,4,101);
INSERT INTO TB_BOOK VALUES(4,'책이네요','장우석',9000,5,100);
INSERT INTO TB_BOOK VALUES(5,'책이래요','조민준',10000,DEFAULT,102);



--3. 회원에 대한 데이터를 담기 위한 회원 테이블(TB_MEMBER)
CREATE TABLE TB_MEMBER(
    MEMBER_NO NUMBER CONSTRAINT MEMBER_PK PRIMARY KEY,
    MEMBER_ID VARCHAR2(20) UNIQUE,
    MEMBER_PWD VARCHAR2(20) CONSTRAINT MEMBER_NN_PWD NOT NULL,
    MEMBER_NAME VARCHAR2(20) CONSTRAINT MEMBER_NN_NAME NOT NULL,
    GENDER CHAR(3) CONSTRAINT MEMBER_CK_GEN CHECK (GENDER IN ('M','F')),
    ADDRESS VARCHAR2(20),
    PHONE VARCHAR2(13),
    STATUS VARCHAR2(20) CONSTRAINT MEMBER_CK_STA CHECK (STATUS IN ('N','Y')),
    ENROLL_DATE DATE DEFAULT SYSDATE CONSTRAINT MEMBER_NN_EN NOT NULL
);

ALTER TABLE MEMBER_UQ ADD CONSTRAINT UNIQUE (MEMBER_ID);

--컬럼명: 
-- MEMBER_NO(회원번호) --기본키(MEMBER_PK)
-- MEMBER_ID(아이디) --중복금지(MEMBER_UQ)
-- MEMBER_PWD(비밀번호) NOT NULL(MEMBER_NN_PWD)
-- MEMBER_NAME(회원명) NOT NULL(MEMBER_NN_NAME)
-- GENDER(성별) 'M' 또는 'F'로 입력되도록 제한(MEMBER_CK_GEN)
--ADDRESS(주소)
--PHONE(연락처)
--STATUS(탈퇴여부) --기본값으로 'N' 그리고 'Y' 혹은 'N'으로 입력되도록 제약조건(MEMBER_CK_STA)
--ENROLL_DATE(가입일) --기본값으로 SYSDATE, NOT NULL 조건(MEMBER_NN_EN)

--5개 정도의 샘플 데이터 추가하기


INSERT INTO TB_MEMBER VALUES(01,'user01','pwd01','김윤정','F','서울','010-1111-1111','N', SYSDATE);
INSERT INTO TB_MEMBER VALUES(02,'user02','pwd02','백가영','F','인천','010-2222-2222','N', SYSDATE);
INSERT INTO TB_MEMBER VALUES(03,'user03','pwd03','박현아','F','인천','010-3333-3333','Y', SYSDATE);
INSERT INTO TB_MEMBER VALUES(04,'user04','pwd04','장우석','M','경기','010-4444-4444','Y', SYSDATE);
INSERT INTO TB_MEMBER VALUES(05,'user05','pwd05','조민준','M','경기','010-5555-5555','Y', SYSDATE);


--4. 도서를 대여한 회원에 대한 데이터를 담기 위한 대여목록 테이블(TB_RENT)
--컬럼:
--RENT_NO(대여번호) --기본키(RENT_PK)
--RENT_MEM_NO(대여회원번호) 
--외래키(RENT_FK_MEM) TB_MEMBER와 참조하도록 ! 이때 부모데이터 삭제 시 NULL값이 되도록 옵션 설정

--RENT_BOOK_NO(대여도서번호)
--외래키(RENT_FK_BOOK) TB_BOOK와 참조하도록 ! 이때 부모데이터 삭제 시 NULL값이 되도록 옵션설정
--RENT_DATE(대여일) --기본값 SYSDATE

CREATE TABLE TB_RENT(
    RENT_NO NUMBER CONSTRAINT RENT_PK PRIMARY KEY,
    RENT_MEM_NO NUMBER CONSTRAINT RENT_FK_MEM REFERENCES TB_MEMBER ON DELETE SET NULL,
    RENT_BOOK_NO NUMBER CONSTRAINT RENT_FK_BOOK REFERENCES TB_BOOK ON DELETE SET NULL,
    RENT_DATE DATE DEFAULT SYSDATE
);

--샘플데이터 3개정도 추가하기
INSERT INTO TB_RENT VALUES(010,01,1,SYSDATE);
INSERT INTO TB_RENT VALUES(020,02,2,SYSDATE);
INSERT INTO TB_RENT VALUES(030,03,3,SYSDATE);

--2번 도서를 대여한 회원의 이름, 아이디, 대여일, 반납예정일(대여일+7)을 조회하시오.

SELECT MEMBER_NAME, MEMBER_ID, RENT_DATE, (RENT_DATE + 7 ) AS "반납예정일"
FROM TB_MEMBER
JOIN TB_RENT ON MEMBER_NO = RENT_MEM_NO
JOIN TB_BOOK ON BK_NO = RENT_BOOK_NO
WHERE BK_NO = 2;


