-- 1. 70년대 생(1970~1979) 중 여자이면서 전씨인 사원의 이름과 주민번호, 부서 명, 직급 조회

SELECT EMP_NAME, EMP_NO, DEPT_TITLE, JOB_CODE
FROM EMPLOYEE
JOIN DEPARTMENT ON(DEPT_ID = DEPT_CODE)
WHERE EMP_NAME LIKE '전%' AND 
     (TO_NUMBER(SUBSTR(EMP_NO,1,2)) BETWEEN 70 AND 79);
     
-- 2. 나이 상 가장 막내의 사원 코드, 사원 명, 나이, 부서 명, 직급 명 조회


SELECT EMP_ID, EMP_NAME, AGE, DEPT_TITLE, JOB_NAME
FROM (SELECT EMP_ID, EMP_NAME, TRUNC(MONTHS_BETWEEN(SYSDATE,TO_DATE('19' || SUBSTR(EMP_NO, 1, 2), 'YYYY')) / 12) AS AGE, DEPT_TITLE, JOB_NAME
      FROM EMPLOYEE E
      JOIN DEPARTMENT D ON E.DEPT_CODE = D.DEPT_ID
      JOIN JOB J ON E.JOB_CODE = J.JOB_CODE
      ORDER BY AGE)
WHERE ROWNUM = 1;    
    
    

/*
SELECT EMP_ID, EMP_NAME
FROM EMPLOYEE
WHERE DEPT_ID = (SELECT DEPT_ID FROM DEPARTMENT WHERE DEPT_TITLE = '영업부');
인라인 뷰 in FROM절

SELECT E.EMP_ID, E.EMP_NAME
FROM (
    SELECT *
    FROM EMPLOYEE
    WHERE DEPT_ID = (SELECT DEPT_ID FROM DEPARTMENT WHERE DEPT_TITLE = '영업부') -- 부서 이름이 영업부인 사람
) E;

*/


-- 3. 이름에 ‘형’이 들어가는 사원의 사원 코드, 사원 명, 직급 조회
SELECT EMP_ID, EMP_NAME, JOB_NAME
FROM EMPLOYEE
JOIN JOB USING(JOB_CODE)
WHERE EMP_NAME LIKE '%형%';

-- 4. 부서코드가 D5이거나 D6인 사원의 사원 명, 직급 명, 부서 코드, 부서 명 조회
SELECT EMP_NAME, JOB_CODE, DEPT_CODE, DEPT_TITLE
FROM EMPLOYEE
JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
WHERE DEPT_CODE ='D5' OR DEPT_CODE = 'D6';

-- 5. 보너스를 받는 사원의 사원 명, 부서 명, 지역 명 조회
SELECT EMP_NAME, DEPT_TITLE, LOCAL_NAME
FROM EMPLOYEE
JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
JOIN LOCATION ON (LOCATION_ID = LOCAL_CODE)
WHERE BONUS IS NOT NULL;

-- 6. 사원 명, 직급 명, 부서 명, 지역 명 조회
SELECT EMP_NAME, JOB_NAME, DEPT_TITLE, LOCAL_NAME
FROM EMPLOYEE
JOIN JOB USING(JOB_CODE)
JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
JOIN LOCATION ON (LOCATION_ID = LOCAL_CODE);

--7. 한국이나 일본에서 근무 중인 사원의 사원 명, 부서 명, 지역 명, 국가 명 조회
SELECT EMP_NAME, DEPT_TITLE, LOCAL_NAME, NATIONAL_NAME
FROM EMPLOYEE
JOIN DEPARTMENT ON (DEPT_ID = DEPT_CODE)
JOIN LOCATION ON (LOCATION_ID = LOCAL_CODE)
JOIN NATIONAL USING (NATIONAL_CODE)
WHERE NATIONAL_CODE IN ('KO','JP');

-- 8. 한 사원과 같은 부서에서 일하는 사원의 이름 조회
SELECT E.EMP_NAME, DEPT_CODE, M.EMP_NAME
FROM EMPLOYEE E
JOIN EMPLOYEE M USING(DEPT_CODE)
WHERE E.EMP_NAME != M.EMP_NAME;

-- 9. 보너스가 없고 직급 코드가 J4이거나 J7인 사원의 이름, 직급 명, 급여 조회(NVL 이용)

SELECT EMP_NAME, JOB_NAME, SALARY
FROM EMPLOYEE
JOIN JOB USING(JOB_CODE)
WHERE BONUS IS NULL AND JOB_CODE IN ('J4','J7');

-- 10. 보너스 포함한 연봉이 높은 5명의 사번, 이름, 부서 명, 직급, 입사일, 순위(?)조회

SELECT *
FROM (
    SELECT EMP_ID, EMP_NAME, DEPT_TITLE, JOB_CODE, HIRE_DATE,
        ROUND((SALARY + (SALARY * NVL(BONUS, 0))) * 12) AS "연봉",
        RANK() OVER (ORDER BY (SALARY + (SALARY * NVL(BONUS, 0))) * 12 DESC) AS "순위"
    FROM EMPLOYEE
    JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID
)
WHERE "순위" <= 5;

-- 11. 부서 별 급여 합계가 전체 급여 총 합의 20%보다 많은 부서의 부서 명, 부서 별 급여 합계 조회
-- 11-1 JOIN과 HAVING 사용
SELECT DEPT_TITLE, SUM(SALARY)
FROM EMPLOYEE
JOIN DEPARTMENT ON (DEPT_ID = DEPT_CODE)
GROUP BY DEPT_TITLE, DEPT_CODE
HAVING SUM(SALARY) > (SELECT SUM(SALARY) * 0.2 FROM EMPLOYEE)
;

-- 11-2 인라인뷰 사용
SELECT DEPT_TITLE, TOTAL_SALARY
FROM (SELECT DEPT_TITLE, SUM(SALARY) AS TOTAL_SALARY
     FROM EMPLOYEE E
     JOIN DEPARTMENT D ON D.DEPT_ID = E.DEPT_CODE
     GROUP BY D.DEPT_TITLE, E.DEPT_CODE
     ) S
WHERE S.TOTAL_SALARY > (
    SELECT SUM(SALARY) * 0.2
    FROM EMPLOYEE
); --> 그룹핑이랑 조인을 한 번에

SELECT DEPT_TITLE, TOTAL_SALARY
FROM (SELECT DEPT_CODE, SUM(SALARY) AS "TOTAL_SALARY"
      FROM EMPLOYEE
      GROUP BY DEPT_CODE)DD
JOIN DEPARTMENT D ON DD.DEPT_CODE = D.DEPT_ID
WHERE TOTAL_SALARY > (SELECT SUM(SALARY) * 0.2 FROM EMPLOYEE);



SELECT DEPT_TITLE, DD.부서별급여합
FROM (SELECT DEPT_CODE, SUM(SALARY) AS "부서별급여합"
      FROM EMPLOYEE
      GROUP BY DEPT_CODE) DD
JOIN DEPARTMENT D ON DD.DEPT_CODE = D.DEPT_ID
WHERE DD.부서별급여합 > (SELECT SUM(SALARY) * 0.2
                      FROM EMPLOYEE);
-- 부서별 급여합을 먼저 구한 다음에, WHERE절에 조건을 걸어서 20% 많은 부서를 찾아냄
-- 그룹핑 하고 나중에 조인 : 이게 유지 보수에 좋다
                



-- 12. 부서명과 부서 별 급여 합계 조회
SELECT D.DEPT_TITLE, SUM(E.SALARY)
FROM EMPLOYEE E
JOIN DEPARTMENT D ON D.DEPT_ID = E.DEPT_CODE
GROUP BY D.DEPT_TITLE;





