--우리반
COMMENT ON COLUMN TBL_BUY.BUY_IDX IS '구매번호';
COMMENT ON COLUMN TBL_BUY.CUSTOMID IS '고객아이디';
COMMENT ON COLUMN TBL_BUY.PCODE IS '제품코드';
COMMENT ON COLUMN TBL_BUY.QUANTITY IS '수량';
COMMENT ON COLUMN TBL_BUY.BUY_DATE IS '구매날짜';

COMMENT ON COLUMN TBL_CUSTOM.CUSTOM_ID IS '고객아이디';
COMMENT ON COLUMN TBL_CUSTOM.NAME IS '고객이름';
COMMENT ON COLUMN TBL_CUSTOM.EMAIL IS '고객이메일';
COMMENT ON COLUMN TBL_CUSTOM.AGE IS '고객나이';
COMMENT ON COLUMN TBL_CUSTOM.REG_DATE IS '가입일';

COMMENT ON COLUMN TBL_PRODUCT.PCODE IS '제품코드';
COMMENT ON COLUMN TBL_PRODUCT.CATEGORY IS '카테고리';
COMMENT ON COLUMN TBL_PRODUCT.PNAME IS '제품명';
COMMENT ON COLUMN TBL_PRODUCT.PRICE IS '가격';