-- 김기석
--문제 1.
SELECT TO_CHAR(B.BUY_DATE + 10, 'MM-DD') AS "배송일자"
     , P.PNAME AS "상품명"
FROM TBL_CUSTOM C
JOIN TBL_BUY B ON C.CUSTOM_ID = B.CUSTOMID
JOIN TBL_PRODUCT P ON B.PCODE = P.PCODE
WHERE C.NAME = '홍길동';

--문제 2.
SELECT P.PNAME AS "상품명"
     , TO_CHAR(BUY_DATE + 10, 'MM-DD')
FROM TBL_CUSTOM C
JOIN TBL_BUY B ON C.CUSTOM_ID = B.CUSTOMID
JOIN TBL_PRODUCT P ON B.PCODE = P.PCODE
WHERE C.EMAIL LIKE '___@%'
    AND LENGTH(SUBSTR(
                C.EMAIL,
                INSTR(C.EMAIL, '@') + 1,
                INSTR(C.EMAIL, '.', INSTR(C.EMAIL, '@')) - INSTR(C.EMAIL, '@') -1
                )) = 5;

-- 김우준
--문제 1.
SELECT C.EMAIL AS "이메일"
     , C.NAME AS "이름"
     , P.PNAME AS "상품명"
     , SUM(P.PRICE * B.QUANTITY) AS "가격의합"
FROM TBL_CUSTOM C
JOIN TBL_BUY B ON C.CUSTOM_ID = B.CUSTOMID
JOIN TBL_PRODUCT P ON B.PCODE = P.PCODE
WHERE C.EMAIL LIKE '%m@%'
GROUP BY C.EMAIL, C.NAME, P.PNAME
ORDER BY C.NAME;  

--문제 2.
SELECT C.NAME AS "고객이름"
     , P.PCODE AS "상품코드"
     , TO_CHAR(B.BUY_DATE, 'YYYY') AS "구매년도"
     , P.PNAME AS "상품명"
FROM TBL_CUSTOM C
JOIN TBL_BUY B ON C.CUSTOM_ID = B.CUSTOMID
JOIN TBL_PRODUCT P ON B.PCODE = P.PCODE
WHERE LENGTH(P.PCODE) = 7;

 
-- 김윤정
--문제 1.
SELECT C.NAME AS "고객명"
     , C.EMAIL AS "이메일"
FROM TBL_CUSTOM C
JOIN TBL_BUY B ON C.CUSTOM_ID = B.CUSTOMID
JOIN TBL_PRODUCT P ON B.PCODE = P.PCODE
WHERE P.PNAME LIKE '%사과%'
    AND TO_CHAR(B.BUY_DATE, 'YYYY') = '2023'
GROUP BY C.NAME, C.EMAIL;

--문제 2.
SELECT *
FROM (
    SELECT P.PNAME AS "상품명"
     , SUM(P.PRICE * B.QUANTITY) AS "총판매금액"
    FROM TBL_PRODUCT P
    JOIN TBL_BUY B ON P.PCODE = B.PCODE
    GROUP BY P.PNAME
    ORDER BY 총판매금액 DESC
)
WHERE ROWNUM = 1;

-- 김이찬
--문제 1.
SELECT ROUND(AVG(AGE), 1) AS "평균나이"
FROM TBL_CUSTOM
WHERE EMAIL NOT LIKE '%daum%'
    AND AGE > 0;

--문제 2.
SELECT SUM(P.PRICE * B.QUANTITY) AS "커플구매총액"
FROM TBL_CUSTOM C
JOIN TBL_BUY B ON C.CUSTOM_ID = B.CUSTOMID
JOIN TBL_PRODUCT P ON B.PCODE = P.PCODE
WHERE C.NAME IN ('홍길동', '박모모');

 
-- 김혜지
--문제 1.
SELECT B.CUSTOMID AS "고객아이디"
     , P.PNAME AS "상품명"
     , SUM(P.PRICE * B.QUANTITY) AS "누적구매금액"
FROM TBL_BUY B
JOIN TBL_PRODUCT P ON B.PCODE = P.PCODE
GROUP BY B.CUSTOMID, P.PNAME
HAVING SUM(P.PRICE * B.QUANTITY) >= 20000
ORDER BY B.CUSTOMID, P.PNAME;

--문제 2.
SELECT C.NAME AS "고객명"
     , P.PNAME AS "상품명"
     , B.QUANTITY AS "수량"
     , B.BUY_DATE AS "구매날짜"
FROM TBL_CUSTOM C
JOIN TBL_BUY B ON C.CUSTOM_ID = B.CUSTOMID
JOIN TBL_PRODUCT P ON B.PCODE = P.PCODE
WHERE P.CATEGORY = 'B1'
ORDER BY B.BUY_DATE DESC;

-- 박선일
--문제 1.
SELECT *
FROM (
    SELECT P.PNAME AS "상품명"
         , SUM(10000 + B.QUANTITY * 20000 + B.QUANTITY * P.PRICE) AS "손실금액"
    FROM TBL_PRODUCT P
    JOIN TBL_BUY B ON P.PCODE = B.PCODE
    WHERE P.CATEGORY LIKE 'B%'
        AND B.BUY_DATE BETWEEN TO_DATE('2023-12-11', 'YYYY-MM-DD')
                           AND TO_DATE('2024-02-10', 'YYYY-MM-DD')
    GROUP BY P.PNAME
    ORDER BY SUM(10000 + B.QUANTITY * 20000 + B.QUANTITY * P.PRICE)DESC
)
WHERE ROWNUM <= 2;

--문제 2.
SELECT 
  L.NAME,
  ROUND((H.연평균 - L.연평균) * L.연수) AS "구매해야할 금액"
FROM 
(
  SELECT *
  FROM (
    SELECT 
      C.NAME,
      NVL(SUM(B.QUANTITY * P.PRICE), 0) AS 총구매,
      CEIL(MONTHS_BETWEEN(SYSDATE, C.REG_DATE - 1) / 12) AS 연수,
      NVL(SUM(B.QUANTITY * P.PRICE), 0) / 
      CEIL(MONTHS_BETWEEN(SYSDATE, C.REG_DATE - 1) / 12) AS 연평균
    FROM TBL_CUSTOM C
    LEFT JOIN TBL_BUY B ON B.CUSTOMID = C.CUSTOM_ID
    LEFT JOIN TBL_PRODUCT P ON B.PCODE = P.PCODE
    GROUP BY C.NAME, C.REG_DATE
    ORDER BY 연평균 ASC
  )
  WHERE ROWNUM = 1
) L,
(
  SELECT *
  FROM (
    SELECT 
      NVL(SUM(B.QUANTITY * P.PRICE), 0) / 
      CEIL(MONTHS_BETWEEN(SYSDATE, C.REG_DATE - 1) / 12) AS 연평균
    FROM TBL_CUSTOM C
    LEFT JOIN TBL_BUY B ON B.CUSTOMID = C.CUSTOM_ID
    LEFT JOIN TBL_PRODUCT P ON B.PCODE = P.PCODE
    GROUP BY C.NAME, C.REG_DATE
    ORDER BY 연평균 DESC
  )
  WHERE ROWNUM = 1
) H;

 
-- 박찬형
--문제 1.
SELECT C.NAME AS "고객명"
     , P.PNAME AS "상품명"
     , B.QUANTITY AS "수량"
FROM TBL_CUSTOM C
JOIN TBL_BUY B ON C.CUSTOM_ID = B.CUSTOMID
JOIN TBL_PRODUCT P ON B.PCODE = P.PCODE
WHERE TO_CHAR(B.BUY_DATE, 'YYYY') = '2023';

--문제 2.
CREATE VIEW VW_TBL 
AS SELECT C.NAME AS "고객명"
        , P.PNAME AS "상품명"
        , B.QUANTITY AS "수량"
        , TO_CHAR(B.BUY_DATE, 'YYYY"년", MM"월", DD"일"') AS "구입날짜"
FROM TBL_CUSTOM C
JOIN TBL_BUY B ON C.CUSTOM_ID = B.CUSTOMID
JOIN TBL_PRODUCT P ON B.PCODE = P.PCODE;

SELECT * FROM VW_TBL;
 
-- 박현아
--문제 1.
SELECT P.PCODE AS "상품코드"
     , P.PNAME AS "상품명"
FROM TBL_PRODUCT P
WHERE P.PCODE NOT IN(
    SELECT B.PCODE
    FROM TBL_BUY B
    WHERE TO_CHAR(B.BUY_DATE, 'YYYY') = '2023'
    GROUP BY B.PCODE
)
ORDER BY P.PCODE;

--문제 2.
SELECT P.PCODE AS "상품코드"
     , P.PNAME AS "상품명"
     , SUM(B.QUANTITY) AS "판매수량"
     , ROUND(SUM(B.QUANTITY) * 100 / 
        (SELECT SUM(QUANTITY)
        FROM TBL_BUY
        WHERE BUY_IDX IN (1002, 1004, 1006, 1008)), 2) AS "비율(%)"
FROM TBL_BUY B
JOIN TBL_PRODUCT P ON B.PCODE = P.PCODE
WHERE B.BUY_IDX IN (1002, 1004, 1006, 1008)
GROUP BY P.PCODE, P.PNAME
ORDER BY P.PCODE;
    
-- 백가영
--문제 1.
SELECT P.PNAME AS "상품명"
     , SUM(P.PRICE * B.QUANTITY) AS "총금액"
FROM TBL_CUSTOM C
JOIN TBL_BUY B ON C.CUSTOM_ID = B.CUSTOMID
JOIN TBL_PRODUCT P ON B.PCODE = P.PCODE
WHERE TO_CHAR(C.REG_DATE, 'YYYY') = '2021'
GROUP BY P.PNAME
ORDER BY "총금액" DESC;

--문제 2.
SELECT ROUND(AVG(C.AGE), 1) AS "평균나이"
FROM TBL_CUSTOM C
WHERE C.CUSTOM_ID IN (
    SELECT B.CUSTOMID
    FROM TBL_BUY B
    GROUP BY B.CUSTOMID, B.BUY_DATE
    HAVING SUM(B.QUANTITY) >= 3
);

 
-- 어수용
--문제 1.
---- 고객 추가 (나이 30 이상 + 이메일 도메인 'korea.com')
INSERT INTO TBL_CUSTOM VALUES ('user01', '김하나', 'hana@korea.com', 33, TO_DATE('2022
01-10','YYYY-MM-DD'));
INSERT INTO TBL_CUSTOM VALUES ('user02', '박둘이', 'park@korea.com', 45, TO_DATE('2021
05-03','YYYY-MM-DD'));
INSERT INTO TBL_CUSTOM VALUES ('user03', '이세영', 'sey@korea.com', 39, TO_DATE('2023
07-15','YYYY-MM-DD'));
INSERT INTO TBL_CUSTOM VALUES ('user04', '최철수', 'ccs@korea.com', 50, TO_DATE('2020
11-11','YYYY-MM-DD'));
INSERT INTO TBL_CUSTOM VALUES ('user05', '정미정', 'mj@naver.com', 28, TO_DATE('2022-04
04','YYYY-MM-DD')); -- 이 사람은 제외 대상
-- 구매 기록 없는 사람
INSERT INTO TBL_CUSTOM VALUES ('user06', '유공백', 'ygb@korea.com', 35, TO_DATE('2021
12-01','YYYY-MM-DD'));

-- 상품 추가 (다양한 가격대, 50,000 이상도 포함)
INSERT INTO TBL_PRODUCT VALUES ('ITEM001', 'B1', '라면세트', 9000);
INSERT INTO TBL_PRODUCT VALUES ('ITEM002', 'A2', '고급과일세트', 72000);
INSERT INTO TBL_PRODUCT VALUES ('ITEM003', 'A1', '사과박스', 33000);
INSERT INTO TBL_PRODUCT VALUES ('ITEM004', 'B2', '혼합간식세트', 51000);
INSERT INTO TBL_PRODUCT VALUES ('ITEM005', 'B1', '쌀10kg', 58000);

-- 구매 내역 추가 (2024년 이후 + 수량 총합 >= 3)
-- user01
INSERT INTO TBL_BUY VALUES (2001, 'user01', 'ITEM001', 2, TO_DATE('2024-01-15', 'YYYY
MM-DD'));
INSERT INTO TBL_BUY VALUES (2002, 'user01', 'ITEM002', 2, TO_DATE('2024-02-10', 'YYYY
MM-DD'));

-- user02
INSERT INTO TBL_BUY VALUES (2003, 'user02', 'ITEM003', 1, TO_DATE('2024-03-05', 'YYYY
MM-DD'));
INSERT INTO TBL_BUY VALUES (2004, 'user02', 'ITEM004', 3, TO_DATE('2024-03-05', 'YYYY
MM-DD'));

-- user03
INSERT INTO TBL_BUY VALUES (2005, 'user03', 'ITEM005', 3, TO_DATE('2024-01-03', 'YYYY
MM-DD'));

-- user04
INSERT INTO TBL_BUY VALUES (2006, 'user04', 'ITEM002', 1, TO_DATE('2024-04-04', 'YYYY
MM-DD'));
INSERT INTO TBL_BUY VALUES (2007, 'user04', 'ITEM005', 3, TO_DATE('2024-04-10', 'YYYY
MM-DD'));

-- user05 (제외 대상이지만 데이터 넣어둠)
INSERT INTO TBL_BUY VALUES (2008, 'user05', 'ITEM001', 1, TO_DATE('2024-05-01', 'YYYY
MM-DD'));

COMMIT;

SELECT B.CUSTOMID
     , C.NAME
     , COUNT(DISTINCT B.PCODE) AS "구매상품종류수"
     , SUM(B.QUANTITY) AS "총구매수량"
FROM TBL_BUY B
JOIN TBL_CUSTOM C ON B.CUSTOMID = C.CUSTOM_ID
WHERE B.BUY_DATE >= TO_DATE('2024-01-01', 'YYYY-MM-DD')
GROUP BY B.CUSTOMID, C.NAME
HAVING SUM(B.QUANTITY) >= 3
ORDER BY SUM(B.QUANTITY) DESC;

--문제 2.
SELECT C.CUSTOM_ID
     , C.NAME
     , C.EMAIL
     , C.AGE
     , NVL(TO_CHAR(MAX(B.BUY_DATE), 'YYYY-MM-DD'), '구매기록없음') AS "최근구매일"
FROM TBL_CUSTOM C
LEFT OUTER JOIN TBL_BUY B ON C.CUSTOM_ID = B.CUSTOMID
WHERE C.AGE >= 30 AND C.EMAIL LIKE '%@korea.com'
GROUP BY C.CUSTOM_ID, C.NAME, C.EMAIL, C.AGE
ORDER BY C.AGE DESC, C.NAME ASC;

-- 오세욱
--문제 1.
SELECT COUNT(DISTINCT CUSTOMID) AS "2023년 구매고객 수"
FROM TBL_BUY
WHERE TO_CHAR(BUY_DATE, 'YYYY') = '2023';

--문제 2.
SELECT C.NAME AS "고객이름"
FROM TBL_CUSTOM C
JOIN TBL_BUY B ON C.CUSTOM_ID = B.CUSTOMID
JOIN TBL_PRODUCT P ON B.PCODE = P.PCODE
WHERE P.PNAME = '청송사과 5kg'
    AND B.QUANTITY = 2
    AND C.AGE = 20;

-- 장우석
--문제 1.
SELECT DISTINCT C.CUSTOM_ID AS "쿠폰 사용 고객"
FROM TBL_CUSTOM C
JOIN TBL_BUY B ON C.CUSTOM_ID = B.CUSTOMID
WHERE B.BUY_DATE <= C.REG_DATE + 30;

--문제 2.
SELECT SUM(P.PRICE * B.QUANTITY) AS "총구매금액"
FROM TBL_CUSTOM C
JOIN TBL_BUY B ON C.CUSTOM_ID = B.CUSTOMID
JOIN TBL_PRODUCT P ON B.PCODE = P.PCODE
WHERE C.CUSTOM_ID = (
    SELECT CUSTOM_ID
    FROM TBL_CUSTOM
    WHERE LENGTH(CUSTOM_ID) = (
        SELECT MAX(LENGTH(CUSTOM_ID))
        FROM TBL_CUSTOM
    )
);

-- 조민준
--문제 1.
SELECT C.NAME AS "이름"
     , P.PNAME AS "상품명"
     , SUM(B.QUANTITY) AS "구매수량"
FROM TBL_CUSTOM C
JOIN TBL_BUY B ON C.CUSTOM_ID = B.CUSTOMID
JOIN TBL_PRODUCT P ON B.PCODE = P.PCODE
WHERE C.EMAIL LIKE '%@daum.net'
GROUP BY C.NAME, P.PNAME
ORDER BY C.NAME;

--문제 2.
UPDATE TBL_CUSTOM
SET AGE = 24
WHERE AGE = 0;

 
-- 최재홍
--문제 1.
SELECT C.NAME AS "고객명"
     , P.PNAME AS "상품명"
FROM TBL_CUSTOM C
JOIN TBL_BUY B ON C.CUSTOM_ID = B.CUSTOMID
JOIN TBL_PRODUCT P ON B.PCODE = P.PCODE
WHERE TO_CHAR(B.BUY_DATE, 'YYYY') IN ('2022', '2024');

--문제 2.
SELECT C.NAME AS "고객명"
     , P.PNAME AS "상품명"
FROM TBL_CUSTOM C
JOIN TBL_BUY B ON C.CUSTOM_ID = B.CUSTOMID
JOIN TBL_PRODUCT P ON B.PCODE = P.PCODE
WHERE P.CATEGORY LIKE 'A%';

-- 한다은
--문제 1.
SELECT P.PNAME AS "상품명"
     , C.NAME AS "고객명"
     , B.BUY_DATE AS "구매일"
FROM TBL_BUY B
JOIN TBL_CUSTOM C ON B.CUSTOMID = C.CUSTOM_ID
JOIN TBL_PRODUCT P ON B.PCODE = P.PCODE
WHERE B.BUY_DATE = (SELECT MAX(BUY_DATE) FROM TBL_BUY);

--문제 2.
SELECT P.PCODE AS "상품코드"
     , P.PNAME AS "상품명"
     , ROUND(AVG(B.QUANTITY), 2) AS "평균구매수량"
FROM TBL_BUY B
JOIN TBL_PRODUCT P ON B.PCODE = P.PCODE
GROUP BY P.PCODE, P.PNAME
HAVING AVG(B.QUANTITY) >= 2;

 
-- 한다현
--문제 1.
SELECT C.NAME AS "고객명"
     , C.EMAIL AS "이메일"
     , SUM(P.PRICE * B.QUANTITY) AS "총구매금액"
     , SUM(B.QUANTITY) AS "총구매수량"
FROM TBL_CUSTOM C
JOIN TBL_BUY B ON C.CUSTOM_ID = B.CUSTOMID
JOIN TBL_PRODUCT P ON B.PCODE = P.PCODE
WHERE C.REG_DATE < TO_DATE('2024-01-01', 'YYYY-MM-DD')
GROUP BY C.NAME, C.EMAIL
HAVING SUM(B.QUANTITY) = (
    SELECT MAX(SUM_QTY)
    FROM (
        SELECT SUM(B.QUANTITY) AS SUM_QTY
        FROM TBL_CUSTOM C
        JOIN TBL_BUY B ON C.CUSTOM_ID = B.CUSTOMID
        WHERE C.REG_DATE < TO_DATE('2024-01-01', 'YYYY-MM-DD')
        GROUP BY C.CUSTOM_ID
    )
);

--문제 2.
INSERT INTO TBL_CUSTOM VALUES('huntrix', '김루미', 'rumi@gmail.com', 20, DEFAULT);   
INSERT INTO TBL_BUY VALUES(9000, 'huntrix', 'DOWON123A', 5, SYSDATE);

SELECT RANK() OVER (ORDER BY SUM(B.QUANTITY) DESC) AS "순위"
     , C.NAME AS "고객명"
     , C.AGE AS "나이"
     , SUM(B.QUANTITY) AS "총구매수량"
     , SUM(P.PRICE * B.QUANTITY) AS "총구매금액"
FROM TBL_CUSTOM C
JOIN TBL_BUY B ON C.CUSTOM_ID = B.CUSTOMID
JOIN TBL_PRODUCT P ON B.PCODE = P.PCODE
GROUP BY C.NAME, C.AGE;
 
-- 홍세민
--문제 1.
SELECT P.PNAME AS "상품명"
     , C.NAME AS "고객명"
     , B.QUANTITY AS "수량"
FROM TBL_PRODUCT P
JOIN TBL_BUY B ON P.PCODE = B.PCODE
JOIN TBL_CUSTOM C ON B.CUSTOMID = C.CUSTOM_ID
WHERE P.PCODE LIKE '%N%';

--문제 2.
SELECT C.NAME AS "고객명"
     , C.EMAIL AS "이메일"
FROM TBL_CUSTOM C
JOIN TBL_BUY B ON C.CUSTOM_ID = B.CUSTOMID
JOIN TBL_PRODUCT P ON B.PCODE = P.PCODE
GROUP BY C.NAME, C.EMAIL
HAVING SUM(P.PRICE * B.QUANTITY) >= 100000;